# Site settings
title: "6th Symposium on Biological Data Visualization"
email: "website@biovis.net"
description: "6th Symposium on Biological Data Visualization"
baseurl: "/biovis_2016"
#url: "http://biovis.github.io/biovis_2016"
url: "http://biovis.net"
conferenceshort: "BioVis 2016"
IEEEconferencedate: "October 24th, 2016"
ISMBconferencedate: "Friday, July 8, 2016"

deadline_submission: "April 29, 2016"
deadline_notification: "June 10, 2016"
deadline_camera: "TBD"

deadline_poster_isbm: "May 15, 2016"
deadline_poster_ieee: "August 26, 2016"

# Build settings
markdown: kramdown

collections:
- talks

google_analytics: "'UA-22015250-1'"
use_analytics: true
