# Site settings
title: "6th Symposium on Biological Data Visualization"
email: "webmaster@dbvis.de"
description: "6th Symposium on Biological Data Visualization"
baseurl: "/biovis_2016"
url: "http://biovis.github.io/biovis_2016"
conferenceshort: "BioVis 2016"
IEEEconferencedate: "IEEE VIS DATE 2016"
ISMBconferencedate: "Friday, July 8, 2016"

deadline_submission: "SUBMISSION DEADLINE"
deadline_notification: "NOTIFICATION DEADLINE"
deadline_camera: "CAMERA DEADLINE"

deadline_poster: "POSTER DEADLINE"

# Build settings
markdown: kramdown

collections:
- talks
