# Site settings
title: "7th Workshop on Biological Data Visualization"
email: "website@biovis.net"
description: "7th Workshop on Biological Data Visualization"
baseurl: "/2017"
#url: "http://biovis.github.io/biovis_2016"
url: "http://biovis.net"
conferenceshort: "BioVis 2017"
IEEEconferencedate: "September 29th, 2017"
ISMBconferencedate: "July 21st, 2016"

IEEE_deadline_submission: "TBD"
IEEE_deadline_notification: "TBD"
IEEE_deadline_camera: "TBD"
IEEE_deadline_poster: "TBD"

ISMB_hl_and_nresearch_submission: "TBD"
ISMB_deadline_poster: "TBD"
ISMB_hl_and_nresearch_notiication: "TBD"


# Build settings
markdown: kramdown

collections:
- posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: true
encoding: utf-8
