# Site settings
title: "BioVis 2017"
email: "website@biovis.net"
description: "Biological Data Visualization"
baseurl: "/2017"
#url: "http://biovis.github.io/biovis_2016"
url: "http://biovis.net"
conferenceshort: "BioVis 2017"
eventNum: "7th"
IEEEconferencedate: "September 29th, 2017"
ISMBconferencedate: "July 24th, 2017"

# Old deadlines so I remember what they're called
# When everything breaks
#IEEE_deadline_submission: "TBD"
#IEEE_deadline_notification: "TBD"
#IEEE_deadline_camera: "TBD"
#IEEE_deadline_poster: "TBD"

#ISMB_hl_and_nresearch_submission: "TBD"
#ISMB_deadline_poster: "TBD"
#ISMB_hl_and_nresearch_notiication: "TBD"

ismb_paper_submission_deadline: "January 26, 2017"
ismb_paper_conditional_accept: "Februrary 28, 2017"
ismb_paper_revised: "March 22, 2017"
ismb_paper_final_acceptance: "April 6, 2017"

biovis_paper_submission_deadline: "April 13, 2017"


ismb_poster_submission_deadline: "May 15, 2017"
ismb_poster_accept: "May 31, 2017"
ismb_poster_oral_notification: "May 31, 2017"

ismb_highlights_submission_deadline: "May 15, 2017"
ismb_late_breaking_accept: "May 31, 2017"

bmc_submission_deadline: ""
bmc_conditional_accept: ""
bmc_final_accpet: ""

# Build settings
markdown: kramdown

collections:
- posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: true
encoding: utf-8
